"""0001 ra tables

Revision ID: 30f65e47d9dc
Revises: 
Create Date: 2026-09-20 00:26:13.894530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30f65e47d9dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handle_hex', sa.String(length=64), nullable=False),
    sa.Column('epoch', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('handle_hex')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('pub_key_hex', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('commitment_hex', sa.String(length=64), nullable=False),
    sa.Column('master_cred_hash_hex', sa.String(length=64), nullable=False),
    sa.Column('sn_hash_hex', sa.String(length=32), nullable=False),
    sa.Column('id_cipher', sa.LargeBinary(), nullable=False),
    sa.Column('cert_level', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commitment_hex'),
    sa.UniqueConstraint('master_cred_hash_hex')
    )
    op.create_table('sub_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.Integer(), nullable=False),
    sa.Column('sub_cred_hash_hex', sa.String(length=64), nullable=False),
    sa.Column('message_hex', sa.String(length=330), nullable=False),
    sa.Column('sig_hex', sa.String(length=128), nullable=False),
    sa.Column('holder_pub_hex', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sub_cred_hash_hex'),
    sa.UniqueConstraint('sub_cred_hash_hex', name='uq_sub_cred_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub_credentials')
    op.drop_table('credentials')
    op.drop_table('users')
    op.drop_table('revocations')
    # ### end Alembic commands ###
